baseURL = "http://localhost:1313"
languageCode = "en-us"
title = "Eric Xue's Web Site"
theme = "Etch"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
dark = "auto"
highlight = true

[menu]
[[menu.main]]
identifier = "posts"
name = "posts"
title = "posts"
url = "/"
weight = 1
[[menu.main]]
identifier = "about"
name = "about"
title = "about"
url = "/about/"
weight = 2
