baseURL = "https://nonrice.github.io"
languageCode = "en-us"
title = "Eric Xue's Web Site"
theme = "hugo-theme-nostyleplease"

[markup.highlight]
tabWidth = 4
codeFences = true
guessSyntax = true
style = 'catppuccin-latte'
