baseURL = "https://widefin.com/"
languageCode = "en-us"
title = "Eric Xue's Website"
theme = "hugo-theme-console"

[markup.highlight]
tabWidth = 4
codeFences = true
guessSyntax = true
style = 'catppuccin-latte'

[[params.navlinks]]
name = "posts/"
url = "posts/"

[[params.navlinks]]
name = "gallery/"
url = "gallery/"