baseURL = "https://nonrice.github.io"
languageCode = "en-us"
title = "Eric Xue's Web Site"
theme = "Etch"

[params]
dark = "auto"
highlight = true

[menu]
[[menu.main]]
identifier = "posts"
name = "posts"
title = "posts"
url = "/"
weight = 1
[[menu.main]]
identifier = "about"
name = "about"
title = "about"
url = "/about/"
weight = 2

[markup.highlight]
tabWidth = 4
codeFences = true
noClasses = false
